# -*- coding: utf-8 -*-
"""Blog-ApI-EditingV7-Github-Pages.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NFo40Z1shofLKot_4W5os-2xhfam8fjA

#Blog Automation Notebook

This notebook generates and publishes written blog posts safely.
"""

!pip install -q google-generativeai
import os, datetime, getpass
import google.generativeai as genai

# Configuration
GEMINI_API_KEY = getpass.getpass("Enter Gemini API key: ")
GITHUB_TOKEN = getpass.getpass("Enter GitHub token: ")
REPO_URL = "https://github.com/RGithub23/BlogColab.git"
REPO_DIR = "BlogColab"
genai.configure(api_key=GEMINI_API_KEY)

# Commented out IPython magic to ensure Python compatibility.

# Clone repo safely
if not os.path.exists(REPO_DIR):
    !git clone https://{GITHUB_TOKEN}@github.com/RGithub23/BlogColab.git
else:
    print("Repo already exists")
# %cd BlogColab

def generate_blog(topic):
    model = genai.GenerativeModel("gemini-flash-latest")
    prompt = f"""Write a structured blog post with title, headings, and conclusion.
Topic: {topic}"""
    return model.generate_content(prompt).text

def save_blog_post(title, content):
    date = datetime.date.today().isoformat()
    filename = f"_posts/{date}-{title.replace(' ', '-').lower()}.md"
    front_matter = f"""---
layout: post
title: "{title}"
date: {date}
---
"""
    with open(filename, "w", encoding="utf-8") as f:
        f.write(front_matter + "\n" + content)
    print(f"Saved {filename}")

TOPIC = "Why the Dodo cannot fly?"
content = generate_blog(TOPIC)
save_blog_post(TOPIC, content)

import datetime
import re
import os

def save_blog_post(title, content):
    date = datetime.date.today().isoformat()   # YYYY-MM-DD
    slug = re.sub(r'[^a-z0-9]+', '-', title.lower()).strip('-')

    filename = f"{date}-{slug}.md"

    # Pre-process the title to handle quotes before embedding in the f-string
    cleaned_title = title.replace('"', "'")

    front_matter = f"""---
layout: post
title: "{cleaned_title}"
date: {date}
---
"""

    with open(filename, "w", encoding="utf-8") as f:
        f.write(front_matter + "\n" + content)

    print(f"✅ Saved blog post as: {filename}")
    return filename

from google.colab import files
files.download(filename)

saved_filename = save_blog_post(TOPIC, content)
print(f"Blog post saved as: {saved_filename}")

from google.colab import files
files.download(saved_filename)

"""Once displayed in github pages look at the written format then add to medium and edit for publication! - Also use the Google App you built for design ideas!

https://github.com/RGithub23/BlogColabV2

https://github.com/RGithub23/BlogAutomationExperiment

https://aistudio.google.com/apps/drive/1A83tqphQVKPtPCzYQIIl-zIO4O4hHtUS
"""